import {
  DashboardSquare03Icon,
  NotificationSquareIcon,
  Calendar03Icon,
  Chat01Icon,
  GraduateMaleIcon,
  StudentsIcon,
  GlobalEducationIcon,
  Money03Icon,
  TeacherIcon,
  ComputerProgramming02Icon,
  OnlineLearning02Icon,
  AnalyticsUpIcon,
  StudentIcon,
  Settings01Icon,
  ArrowRight02Icon,
  Wallet01Icon,
  Payment02Icon,
  Discount01Icon,
  SchoolReportCardIcon,
  Calendar02Icon,
  Task01Icon,
  UserSettings01Icon,
  CourseIcon,
  Store01Icon,
  Analytics01Icon,
  InvestigationIcon,
  BankIcon,
  GraduationScrollIcon,
  MailSend01Icon,
} from "@hugeicons/core-free-icons";

import { MenuItem, UserRole } from "../lib/types";

// Menu items configuration with role-based access
export const menuItems: MenuItem[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: DashboardSquare03Icon,
    href: "dashboard",
    roles: ["admin", "teacher", "parent", "student"],
  },
  {
    id: "notice-board",
    label: "Notice Board",
    icon: NotificationSquareIcon,
    href: "/notice-board",
    roles: ["admin", "teacher", "parent", "student"],
    badge: 4,
  },
  {
    id: "calendar",
    label: "Calendar",
    icon: Calendar03Icon,
    href: "/calendar",
    roles: ["admin", "teacher", "parent"],
    badge: 1,
  },
  {
    id: "messages",
    label: "Messages",
    icon: Chat01Icon,
    href: "/messages",
    roles: ["admin", "teacher", "parent", "student"],
    badge: 3,
  },
  {
    id: "timetable",
    label: "Timetable",
    icon: Chat01Icon,
    href: "/timetable",
    roles: ["student"],
    badge: 3,
  },
  {
    id: "separator",
    label: "",
    href: "",
    roles: ["admin", "teacher", "parent", "student"],
  },
  {
    id: "myclass",
    label: "My Class",
    icon: TeacherIcon,
    href: "/my-class",
    roles: ["teacher"],
  },
  {
    id: "mycourses",
    label: "My Courses",
    icon: CourseIcon,
    href: "/my-courses",
    roles: ["student", "teacher"],
  },
  {
    id: "assignments",
    label: "Assignments & Quizzes",
    icon: TeacherIcon,
    href: "/assignments",
    roles: ["student"],
  },
  {
    id: "mygrades",
    label: "My Grades",
    icon: SchoolReportCardIcon,
    href: "/my-grades",
    roles: ["student"],
  },
  {
    id: "grades&report",
    label: "Grades & Report Card",
    icon: SchoolReportCardIcon,
    href: "/grades-report-card",
    roles: ["parent"],
  },
  {
    id: "timetable",
    label: "Timetable",
    icon: Calendar02Icon,
    href: "/timetable",
    roles: ["parent"],
  },
  {
    id: "admissions",
    label: "Admissions",
    icon: GraduateMaleIcon,
    href: "/admissions",
    roles: ["admin"],
  },
  {
    id: "students",
    label: "Students",
    icon: StudentsIcon,
    href: "/students",
    roles: ["admin"],
  },
  {
    id: "staff-management",
    label: "Staff Management",
    icon: TeacherIcon,
    href: "/staff-management",
    roles: ["admin"],
  },
  {
    id: "separator",
    label: "",
    href: "",
    roles: ["admin", "teacher", "parent", "student"],
  },
  {
    id: "questionbank",
    label: "Question Bank",
    icon: BankIcon,
    href: "/question-bank",
    roles: ["teacher"],
  },
  {
    id: "gradeentryportal",
    label: "Grade Entry Portal",
    icon: GraduationScrollIcon,
    href: "/grade-entry-portal",
    roles: ["teacher"],
  },
  {
    id: "mywallet",
    label: "My Wallet",
    icon: Wallet01Icon,
    href: "/my-wallet",
    roles: ["student", "teacher"],
  },
  {
    id: "leaverequestportal",
    label: "Leave Request Portal",
    icon: MailSend01Icon,
    href: "/leave-request-portal",
    roles: ["teacher"],
  },
  {
    id: "parentmywallet",
    label: "Tunde's Wallet",
    icon: Wallet01Icon,
    href: "/wallet",
    roles: ["parent"],
  },
  {
    id: "fees&payment",
    label: "Fees & Payment",
    icon: Payment02Icon,
    href: "/fee-payment-management",
    roles: ["parent"],
  },
  {
    id: "feesrequestportal",
    label: "Fees/ Request Portal",
    icon: Discount01Icon,
    href: "/fee-request-portal",
    roles: ["parent"],
  },
  {
    id: "finance",
    label: "Finance",
    icon: Money03Icon,
    href: "/finance",
    roles: ["admin"],
    children: [
      // {
      //   id: "financedashboard",
      //   label: "Finance Dashboard",
      //   icon: ArrowRight02Icon,
      //   href: "/finance",
      //   roles: ["admin"],
      // },
      {
        id: "fee&revenue",
        label: "Fee & Revenue Management",
        icon: ArrowRight02Icon,
        href: "/finance/fee-revenue-management",
        roles: ["admin"],
      },
      {
        id: "dailyoperations",
        label: "Daily Operations & Treasury",
        icon: ArrowRight02Icon,
        href: "/finance/daily-operations-treasury",
        roles: ["admin"],
      },
      {
        id: "reporting&compliance",
        label: "Reporting & Compliance",
        icon: ArrowRight02Icon,
        href: "/finance/reporting-and-compliance",
        roles: [],
      },
    ],
  },
  {
    id: "separator",
    label: "",
    href: "",
    roles: ["admin", "teacher", "parent", "student"],
  },
  {
    id: "personaltaskmanager",
    label: "Personal Task Manager",
    icon: Task01Icon,
    href: "/personal-task-manager",
    roles: ["student"],
  },
  {
    id: "myprofile",
    label: "My Profile",
    icon: UserSettings01Icon,
    href: "/my-profile",
    roles: ["student"],
  },
  {
    id: "academic-management",
    label: "Academic Management",
    icon: GlobalEducationIcon,
    href: "/academic",
    roles: ["admin"],
    children: [
      {
        id: "academicdashboard",
        label: "Academic Dashboard",
        icon: ArrowRight02Icon,
        href: "academic/dashboard",
        roles: ["admin"],
      },
      {
        id: "curriculummanagement",
        label: "Curriculum Management",
        icon: ArrowRight02Icon,
        href: "academic/curriculum-management",
        roles: ["admin"],
      },
      {
        id: "assessment&grading",
        label: "Assessment & Grading",
        icon: ArrowRight02Icon,
        href: "academic/assessment-grading",
        roles: ["admin"],
      },
    ],
  },
  {
    id: "cbt-management",
    label: "CBT Management",
    icon: ComputerProgramming02Icon,
    href: "/cbt-management",
    roles: ["admin"],
  },
  {
    id: "learning-management",
    label: "Learning Management",
    icon: OnlineLearning02Icon,
    href: "/learning-management",
    roles: ["admin"],
  },
  {
    id: "separator",
    label: "",
    href: "",
    roles: ["admin"],
  },
  {
    id: "report-analysis",
    label: "Report & Analysis",
    icon: AnalyticsUpIcon,
    href: "/reports",
    roles: [],
  },
  {
    id: "alumni-management",
    label: "Alumni Management",
    icon: StudentIcon,
    href: "/alumni-management",
    roles: ["admin"],
  },
  {
    id: "terminal",
    label: "Terminal",
    icon: Store01Icon,
    href: "/store",
    roles: ["canteen"],
  },
  {
    id: "sales",
    label: "Sales",
    icon: Analytics01Icon,
    href: "/sales",
    roles: ["canteen"],
  },
  {
    id: "inventory",
    label: "Inventory",
    icon: InvestigationIcon,
    href: "/inventory",
    roles: ["canteen"],
  },
  {
    id: "notice",
    label: "Notice",
    icon: NotificationSquareIcon,
    href: "/notice",
    roles: ["canteen"],
  },
  {
    id: "system-settings",
    label: "System Settings",
    icon: Settings01Icon,
    href: "/settings",
    roles: ["admin", "teacher", "parent", "canteen"],
  },
];
